config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update] do
    get '/follow' => 'relationships#follow'
    get '/follower' => 'relationships#follower'
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
	end
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    user_path(resource.id) # サインイン後に遷移するpathを設定
  end
  def after_sign_in_path_for(resource)
    user_path(resource.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
  	@book = Book.find(params[:book_id])
  	comment = current_user.book_comments.new(book_comment_params)
  	comment.book_id = @book.id
  	comment.save
  	redirect_to book_path(@book)
  end
  def destroy
  	BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  	redirect_to book_path(params[:book_id])
  end
  private
  def book_comment_params
  	params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
    book_comments = BookComment.all
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books = Book.all
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	 before_action :authenticate_user!
  def create
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.new(book_id: @book.id)
  	favorite.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	favorite = current_user.favorites.find_by(book_id: @book.id)
  	favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
before_action :set_user, only:[:create, :destroy]

  def create
    following = current_user.follow(@user)
    following.save
    redirect_to request.referer

  end

  def destroy
    following = current_user.unfollow(@user)
    following.destroy
    redirect_to request.referer
  end

  def follow
    @user = User.find(params[:user_id])
    @currentuser = current_user
  end
  def follower
    @user = User.find(params[:user_id])
    @currentuser = current_user
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = @book.user

  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model: [book, @book_comment], remote: true) do |f| %>
	<div class="row">
		<div class="col-sm-12">
			<%= f.text_area :comment, rows:'5', class: "form-control" %>
		</div>
	</div>
		<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
	<tr>
		<td>
			<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 40, 40, fallback: "no-image-mini.jpg") %>
		</td>
		<td>
			<%= book_comment.user.name %>
		</td>
		<td>
			<% if book_comment.user == current_user %>
				<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
			<% end %>
		</td>
	</tr>
<% end %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book", class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
<% if @book.errors.any? %>
	<div id="error_explanation">
		<h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    	<ul>
        	<% @book.errors.full_messages.each do |message| %>
            	<li><%= message %></li>
          	<% end %>
		</ul>
	</div>
<% end %>
		<h1>Editing Book</h1>

		<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>


	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
	<div id="error_explanation">
		<h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    	<ul>
        	<% @book.errors.full_messages.each do |message| %>
            	<li><%= message %></li>
          	<% end %>
		</ul>
	</div>
<% end %>
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
							<div id="favolites_<%= book.id %>">
								<%= render partial: 'favorites/favorite', locals: { book: book } %>
							</div>
						</td>
						<td>
							コメント数：<%= book.book_comments.count %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<td>
							<div id="favolites_<%= @book.id %>">
								<%= render partial: 'favorites/favorite', locals: { book: @book } %>
							</div>
					</td>
					<td>
						コメント数：<%= @book.book_comments.count %>
					</td>
					<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			<div id="comments_area">
				<%= render partial: 'book_comments/index', locals: { book: @book, book_comments: @book_comments } %>
			</div>
			</table>
			<div>
				<%= render partial: 'book_comments/form', locals: { book: @book, book_comments: @book_comments } %>
			</div>
	</div>
</div>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
	<% if book.favorited_by?(current_user) %>
		<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
		  	<span class="glyphicon glyphicon-heart" aria-hidden="true red"></span>
		    <%= book.favorites.count %>
		 <% end %>
		<% else %>
		 <%= link_to book_favorites_path(book), method: :post, remote: true do %>
		    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
		   <%= book.favorites.count %>
		  <% end %>
	<% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favolites_<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { book: @book }) %>");

app/views/favorites/destroy.js.erb
$("#favolites_<%= @book.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { book: @book }) %>");

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>

    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/relationships/follow.html.erb
<h1>Follow Users</h1>
<% if @user.followings.present? %>
	<table class="table">
			<tr>
				<th>image</th>
				<th>name</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		<tbody>
			<% @user.followings.each do |user| %>
				<tr>
					<td>
						<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>
					</td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td>
						<% unless current_user == user %>
						  <% if current_user.following?(user) %>
						    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
						      <%= hidden_field_tag :follow_id, user.id %>
						      <%= f.submit 'フォローを外す' %>
						    <% end %>
						  <% else %>
						    <%= form_for(current_user.relationships.build) do |f| %>
						      <%= hidden_field_tag :follow_id, user.id %>
						      <%= f.submit 'フォローする' %>
						    <% end %>
						  <% end %>
						<% end %>
			        </td>
					<td><%= link_to "Show", user_path(@currentuser) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
  <p>ユーザーはいません。</p>
<% end %>

app/views/relationships/follower.html.erb
<h1>Follower Users</h1>
<% if @user.followers.present? %>
	<table class="table">
			<tr>
				<th>image</th>
				<th>name</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		<tbody>
			<% @user.followers.each do |follow| %>
				<tr>
					<td>
						<%= attachment_image_tag follow, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>
					</td>
					<td><%= follow.name %></td>
					<td>フォロー数：<%= follow.followings.count %></td>
					<td>フォロワー数：<%= follow.followers.count %></td>
					<td><%= link_to "Show", user_path(@currentuser) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
  <p>ユーザーはいません。</p>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th>
			<%= link_to user_follow_path(user) do %>
				<%= user.followings.count %>
			<% end %>
			</th>
	</tr>
	<tr>
		<th>followers</th>
		<th>
			<%= link_to user_follower_path(user) do %>
				<%= user.followers.count %>
			<% end %>
		</th>
	</tr>
</table>

<% if current_user == user %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>
	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.followings.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td>
						<% unless current_user == user %>
						  <% if current_user.following?(user) %>
						    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
						      <%= hidden_field_tag :follow_id, user.id %>
						      <%= f.submit 'フォローを外す' %>
						    <% end %>
						  <% else %>
						    <%= form_for(current_user.relationships.build) do |f| %>
						      <%= hidden_field_tag :follow_id, user.id %>
						      <%= f.submit 'フォローする' %>
						    <% end %>
						  <% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<!--users一覧 -->
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

			<% unless current_user == @user %>
				<% if current_user.following?(@user) %>
					<%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
						<%= hidden_field_tag :follow_id, @user.id %>
						   <%= f.submit 'フォローを外す', class: 'btn btn-primary btn-block' %>
						<% end %>
						<% else %>
						  <%= form_for(current_user.relationships.build) do |f| %>
						 <%= hidden_field_tag :follow_id, @user.id %>
						   <%= f.submit 'フォローする', class: 'btn btn-success btn-block' %>
						 <% end %>
					<% end %>
				<% end %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>